apiVersion: v1
kind: Service
metadata:
  name: node-observability-app
  namespace: app
  labels:
    app: node-observability-app
spec:
  selector:
    app: node-observability-app
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
